//
//  SDListViewItem.m
//  SingleListExample
//
//  Created by Steven Degutis on 10/26/09.
//

#import "SDListViewItem.h"

#import "SDListView+Private.h"

@implementation SDListViewItem

@dynamic representedObject;
@dynamic view;

@synthesize listView;

@synthesize selected;

- (id) copyWithZone:(NSZone *)zone {
	return [[[self class] alloc] initWithNibName:[self nibName] bundle:[self nibBundle]];
}

- (CGFloat) heightForGivenWidth:(CGFloat)width {
	return 70.0; // generated by fair dice roll.
				 // guaranteed to be random.
}

- (void) setListView:(SDListView*)someListView {
	listView = someListView;
}

- (void) setSelected:(BOOL)isSelected {
	[self willChangeValueForKey:@"selected"];
	selected = isSelected;
	[self didChangeValueForKey:@"selected"];
}

- (void) noteViewHeightChanged {
	[self.listView noteHeightChangedForItem:self];
}

@end
